
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = xilkernel
 PARAMETER OS_VER = 4.00.a
 PARAMETER PROC_INSTANCE = ppc405_0
 PARAMETER STDIN = RS232
 PARAMETER STDOUT = RS232
 PARAMETER SYSINTC_SPEC = xps_intc_0
 PARAMETER config_sema = true
 PARAMETER config_time = true
 PARAMETER enhanced_features = true
 PARAMETER config_yield = true
 PARAMETER pthread_stack_size = 65536
 PARAMETER static_pthread_table = ((main_thread,1))
 PARAMETER sched_type = SCHED_PRIO
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_ppc405
 PARAMETER DRIVER_VER = 1.10.b
 PARAMETER HW_INSTANCE = ppc405_0
 PARAMETER COMPILER = powerpc-eabi-gcc
 PARAMETER ARCHIVER = powerpc-eabi-ar
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = mpmc
 PARAMETER DRIVER_VER = 3.00.a
 PARAMETER HW_INSTANCE = DDR_SDRAM_32Mx16
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 1.14.a
 PARAMETER HW_INSTANCE = RS232
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = lltemac
 PARAMETER DRIVER_VER = 2.00.a
 PARAMETER HW_INSTANCE = TriMode_MAC_GMII
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = llfifo
 PARAMETER DRIVER_VER = 1.01.a
 PARAMETER HW_INSTANCE = TriMode_MAC_GMII_fifo
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = pulse_controller
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = pulse_controller_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = xps_bram_if_cntlr_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 1.11.a
 PARAMETER HW_INSTANCE = xps_intc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 2.01.a
 PARAMETER HW_INSTANCE = xps_spi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 2.01.a
 PARAMETER HW_INSTANCE = xps_spi_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 2.01.a
 PARAMETER HW_INSTANCE = xps_spi_2
END

BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = lwip130
 PARAMETER LIBRARY_VER = 1.00.b
 PARAMETER PROC_INSTANCE = ppc405_0
 PARAMETER api_mode = SOCKET_API
END

