
 PARAMETER VERSION = 2.2.0


BEGIN OS
 PARAMETER OS_NAME = xilkernel
 PARAMETER OS_VER = 4.00.a
 PARAMETER PROC_INSTANCE = ppc405_0
 PARAMETER sysintc_spec = xps_intc_0
 PARAMETER stdout = RS232
 PARAMETER stdin = RS232
 PARAMETER enhanced_features = true
 PARAMETER config_yield = true
 PARAMETER config_sema = true
 PARAMETER max_sem_waitq = 20
 PARAMETER max_sem = 50
 PARAMETER config_time = true
 PARAMETER max_tmrs = 20
 PARAMETER max_readyq = 20
 PARAMETER max_pthread_mutex = 20
 PARAMETER pthread_stack_size = 32768
 PARAMETER static_pthread_table = ((main_thread,1))
END


BEGIN PROCESSOR
 PARAMETER DRIVER_NAME = cpu_ppc405
 PARAMETER DRIVER_VER = 1.11.a
 PARAMETER HW_INSTANCE = ppc405_0
 PARAMETER COMPILER = powerpc-eabi-gcc
 PARAMETER ARCHIVER = powerpc-eabi-ar
END


BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = jtagppc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = bram
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = xps_bram_if_cntlr_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = plb_bram_if_cntlr_1_bram
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = uartlite
 PARAMETER DRIVER_VER = 1.14.a
 PARAMETER HW_INSTANCE = RS232
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = lltemac
 PARAMETER DRIVER_VER = 1.00.b
 PARAMETER HW_INSTANCE = TriMode_MAC_GMII
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = mpmc
 PARAMETER DRIVER_VER = 1.01.a
 PARAMETER HW_INSTANCE = DDR_SDRAM_32Mx16
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = llfifo
 PARAMETER DRIVER_VER = 1.01.a
 PARAMETER HW_INSTANCE = TriMode_MAC_GMII_fifo
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = clock_generator_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = generic
 PARAMETER DRIVER_VER = 1.00.a
 PARAMETER HW_INSTANCE = proc_sys_reset_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = intc
 PARAMETER DRIVER_VER = 1.11.a
 PARAMETER HW_INSTANCE = xps_intc_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 2.01.b
 PARAMETER HW_INSTANCE = xps_spi_0
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 2.01.b
 PARAMETER HW_INSTANCE = xps_spi_1
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = spi
 PARAMETER DRIVER_VER = 2.01.b
 PARAMETER HW_INSTANCE = xps_spi_2
END

BEGIN DRIVER
 PARAMETER DRIVER_NAME = pulse_controller
 PARAMETER DRIVER_VER = 3.01.a
 PARAMETER HW_INSTANCE = pulse_controller_0
END


BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = lwip
 PARAMETER LIBRARY_VER = 3.00.a
 PARAMETER PROC_INSTANCE = ppc405_0
 PARAMETER api_mode = SOCKET_API
 PARAMETER phy_link_speed = CONFIG_LINKSPEED1000
END

BEGIN LIBRARY
 PARAMETER LIBRARY_NAME = xilmfs
 PARAMETER LIBRARY_VER = 1.00.a
 PARAMETER base_address = 0x03000000
 PARAMETER PROC_INSTANCE = ppc405_0
 PARAMETER need_utils = true
 PARAMETER numbytes = 266000
 PARAMETER init_type = MFSINIT_IMAGE
END

